name: Feature Request
description: Suggest an idea or improvement for this project.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature or improvement! Please fill out the details below clearly and concisely.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we reach you if we have further questions?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: feature-description
    attributes:
      label: What feature would you like?
      description: Describe clearly what the feature or improvement is.
      placeholder: "I would like to have..."
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Describe the Use Case
      description: Explain the scenario or use case for this feature. Why is this important or valuable?
      placeholder: "This feature would be helpful because..."
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low
        - Medium
        - High
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Add any other context or screenshots about the feature request here.
        
        Tip: You can attach images or documents by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
